server: 
  port: 8080
  
spring:
    jpa:
        database: H2
        hibernate:
            ddl-auto: update

    datasource:
        url: jdbc:h2:mem:testdb
        username: root
        password: 
        driver-class-name: org.h2.Driver
 